"____Arun Kumar Reddy____";
figure();
img = imread("Circuit.jpg");
subplot(1,3,1),imshow(img);title("Original Image");
mask=ones(3)./9;
filteredIm=uint8(AverageFiltering(img,mask));
subplot(1,3,2),imshow(filteredIm);title("3x3 filtered Image");
maskk=ones(5)./25;
filteredIm=uint8(AverageFiltering(img,maskk));
subplot(1,3,3),imshow(filteredIm);title("5x5 filtered Image");
pause;
"____Finished Problem 1____";
figure();
subplot(1,3,1),imshow(img);title("Original Image");
mask=[1 2 1;2 4 2;1 2 1];
filteredIm=uint8(MedianFiltering(img,mask));
subplot(1,3,2),imshow(filteredIm);title("weighted median filter Image");
maskk=[1 1 1 1 1;1 1 1 1 1;1 1 1 1 1;1 1 1 1 1;1 1 1 1 1];
filteredIm=uint8(MedianFiltering(img,maskk));
subplot(1,3,3),imshow(filteredIm);title("standard median filter Image");
pause;
"____Finished Problem 2____";
figure();
mim = imread('Moon.jpg');
laplacianFilter = [1 1 1;1 -8 1; 1 1 1];
moonFilteredImg = imfilter(double(mim),laplacianFilter,'conv');
oldMin = double(min(moonFilteredImg(:)));
oldMax = double(max(moonFilteredImg(:)));
scaledMoonIm = (moonFilteredImg - oldMin)/(oldMax - oldMin);
scaledMoonIm = uint8(255*scaledMoonIm);
moonFilteredImg = uint8(moonFilteredImg);
moonEnhancedImg = mim + moonFilteredImg;
subplot(2,2,1),imshow(mim),title('Original Image');
subplot(2,2,2),moonFilteredImg(moonFilteredImg>255) = 255;
moonFilteredImg(moonFilteredImg<0) = 0;imshow(moonFilteredImg)
title('Filtered Image')
subplot(2,2,3),imshow(scaledMoonIm),title('Scaled Image');
subplot(2,2,4),imshow(moonEnhancedImg),title('Enhanced Image');
"____Finished Problem 3____";
figure();
img=im2gray(imread("Rice.jpg"));
bin=20;
[edges,edgeHist] = FindEdgeInfo(img,bin);
bar(edgeHist);
pause;
"____Finished Problem 4____";
textIm = imread('Text.gif');
text1Im = imread('Text1.gif');
RemoveStreaks(textIm);
RemoveStreaks(text1Im);
pause;
'-----Finish Solving Problem 5-----';
close all;

